# tekton-pipeline values.yaml
image:
  registry: registry.playcekube.local:5000

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


# If is enable tekton dashboard is install
tekton-dashboard:
  enabled: true

  image:
    registry: registry.playcekube.local:5000

  ingress:
    enabled: true
   
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: tekton.playcek8s.playcekube.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: tekton-tls
        hosts:
          - tekton.playcek8s.playcekube.local
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

