---
_meta:
  type: "rolesmapping"
  config_version: 2

all_access:
  reserved: false
  backend_roles:
  - "admin"
  description: "Maps admin to all_access"

own_index:
  reserved: false
  users:
  - "*"
  description: "Allow full access to an index named like the username"

kibana_user:
  reserved: false
  backend_roles:
  - "kibanauser"
  description: "Maps kibanauser to kibana_user"

kibana_server:
  reserved: true
  users:
  - "kibanaserver"

logstash:
  reserved: false
  backend_roles:
  - "logstash"

curator:
  reserved: false
  backend_roles:
  - "curator"

