#!/bin/sh
BASEDIR=$(dirname $(readlink -f $0))

if [ -f ${BASEDIR}/../../playcekube.conf ]; then
  . ${BASEDIR}/../../playcekube.conf
fi

# ntp(chrony) server restart
systemctl restart chronyd

# registry container restart
docker stop playcekube_registry 2> /dev/null
docker rm playcekube_registry 2> /dev/null
docker run -d --name playcekube_registry \
--restart always \
-v ${PLAYCE_DIR}/playcekube/deployer/registry:/etc/docker/registry \
-v ${PLAYCE_DATADIR}/registry:/var/lib/registry \
-p 5000:5000 \
docker.io/library/registry:2.7.1

# dns(bind9) container restart
docker stop playcekube_bind9 2> /dev/null
docker rm playcekube_bind9 2> /dev/null
docker run -d --name playcekube_bind9 \
--restart always \
-e TZ=Asia/Seoul \
-v ${PLAYCE_DIR}/playcekube/deployer/bind9/config:/etc/bind \
-v ${PLAYCE_DIR}/playcekube/deployer/bind9/cache:/var/cache/bind \
-v ${PLAYCE_DIR}/playcekube/deployer/bind9/records:/run/name \
-p 53:8053 \
-p 53:8053/udp \
docker.io/ubuntu/bind9:9.16-21.10_edge

# repository (nginx) container restart
docker stop playcekube_repositories 2> /dev/null
docker rm playcekube_repositories 2> /dev/null
docker run -d --name playcekube_repositories \
--restart always \
-v ${PLAYCE_DIR}/playcekube/deployer/nginx/repositories.conf:/etc/nginx/nginx.conf \
-v ${PLAYCE_DIR}/playcekube/deployer/nginx/servers.conf:/etc/nginx/servers.conf \
-v ${PLAYCE_DIR}/playcekube/deployer/nginx/ssl:/etc/nginx/ssl \
-v ${PLAYCE_DATADIR}/repositories:/repositories \
-p 80:80 \
-p 443:443 \
docker.io/library/nginx:1.20.2

## resolv.conf modify
cat << EOF > /etc/resolv.conf
# generated by playcekube
nameserver 127.0.0.1
nameserver ${UPSTREAM_DNS}
EOF

# hosts modify
sed -i "/registry.${PLAYCE_DOMAIN}/d" /etc/hosts
cat << EOF >> /etc/hosts
${PLAYCE_DEPLOYER} registry.${PLAYCE_DOMAIN} repository.${PLAYCE_DOMAIN} repositories.${PLAYCE_DOMAIN}
EOF

